/*
 *  Copyright 2013 Cloud4SOA, www.cloud4soa.eu
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


package eu.cloud4soa.c4sgitservice.dao;


import java.util.List;

import eu.cloud4soa.c4sgitservice.datamodel.User;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

/**
 * Created with IntelliJ IDEA.
 * User: pgouvas
 * Date: 8/2/12
 * Time: 12:30 PM
 */
public interface UserRepository extends JpaRepository<User,Long>{
    
    /*
     * Will produce autogenerated DAO Impl
     */
    public User findByUserId(Long userid);

    public List<User> findByUsername(String username);

    public List<User> findByUsernameAndPassword(String username,String password);

    //public List<User> findByUserIdLike(String userid);
    
    //@Query("select count (*) from USERS u where u.userId like ?1 ")
    //public long countByUserIdLike(String userid);
            
    //public List<User> findByUserIdLike(String userid,Pageable page);
        
    //public User findByUserIdAndDorCode(String userid,Long dorcode);
    
}