/*
 *  Copyright 2013 Cloud4SOA, www.cloud4soa.eu
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


/* Generated By:JavaCC: Do not edit this line. CloudProfilesParserConstants.java */
package eu.cloud4soa.cli.profiles.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CloudProfilesParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROFILE = 6;
  /** RegularExpression Id. */
  int DEVELOPER = 7;
  /** RegularExpression Id. */
  int PROVIDER = 8;
  /** RegularExpression Id. */
  int APPLICATION = 9;
  /** RegularExpression Id. */
  int PAAS_OFFERING = 10;
  /** RegularExpression Id. */
  int ACCOUNT = 11;
  /** RegularExpression Id. */
  int SOFTWARE = 12;
  /** RegularExpression Id. */
  int HARDWARE = 13;
  /** RegularExpression Id. */
  int NETWORK_RESOURCE = 14;
  /** RegularExpression Id. */
  int BOX = 15;
  /** RegularExpression Id. */
  int COMPUTE = 16;
  /** RegularExpression Id. */
  int HTTP_REQUESTS = 17;
  /** RegularExpression Id. */
  int STORAGE_RESOURCE = 18;
  /** RegularExpression Id. */
  int CHANNELS = 19;
  /** RegularExpression Id. */
  int API = 20;
  /** RegularExpression Id. */
  int CLI = 21;
  /** RegularExpression Id. */
  int WebInterface = 22;
  /** RegularExpression Id. */
  int LBRACE = 23;
  /** RegularExpression Id. */
  int RBRACE = 24;
  /** RegularExpression Id. */
  int COLON = 25;
  /** RegularExpression Id. */
  int BANDWIDTH = 26;
  /** RegularExpression Id. */
  int LATENCY = 27;
  /** RegularExpression Id. */
  int SPEED = 28;
  /** RegularExpression Id. */
  int MEMORY = 29;
  /** RegularExpression Id. */
  int CACHE = 30;
  /** RegularExpression Id. */
  int CAPACITY = 31;
  /** RegularExpression Id. */
  int FIRSTNAME = 32;
  /** RegularExpression Id. */
  int SURNAME = 33;
  /** RegularExpression Id. */
  int USERNAME = 34;
  /** RegularExpression Id. */
  int PASSWORD = 35;
  /** RegularExpression Id. */
  int ACRONYM = 36;
  /** RegularExpression Id. */
  int COMMAND = 37;
  /** RegularExpression Id. */
  int DIGEST = 38;
  /** RegularExpression Id. */
  int URL = 39;
  /** RegularExpression Id. */
  int PROGRAMMING_LANGUAGE = 40;
  /** RegularExpression Id. */
  int INFORMATION_RETURNED = 41;
  /** RegularExpression Id. */
  int APPLICATION_CODE = 42;
  /** RegularExpression Id. */
  int SIZE = 43;
  /** RegularExpression Id. */
  int FILE_NAME = 44;
  /** RegularExpression Id. */
  int CATEGORY = 45;
  /** RegularExpression Id. */
  int COMPONENT = 46;
  /** RegularExpression Id. */
  int DESCRIPTION = 47;
  /** RegularExpression Id. */
  int BIRTHDAY = 48;
  /** RegularExpression Id. */
  int EMAIL = 49;
  /** RegularExpression Id. */
  int VERSION = 50;
  /** RegularExpression Id. */
  int LICENSE = 51;
  /** RegularExpression Id. */
  int LICENSE_TYPE = 52;
  /** RegularExpression Id. */
  int CORES = 53;
  /** RegularExpression Id. */
  int ARCHITECTURE = 54;
  /** RegularExpression Id. */
  int OPERATION = 55;
  /** RegularExpression Id. */
  int ARCHITECTURE_VALUE = 56;
  /** RegularExpression Id. */
  int FLOATING_POINT = 57;
  /** RegularExpression Id. */
  int NATURAL_NUMBER = 58;
  /** RegularExpression Id. */
  int DATE_US = 59;
  /** RegularExpression Id. */
  int STRING = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"profile\"",
    "\"developer\"",
    "\"provider\"",
    "\"application\"",
    "\"paas_offering\"",
    "\"account\"",
    "\"software\"",
    "\"hardware\"",
    "\"network_resource\"",
    "\"box\"",
    "\"compute\"",
    "\"http_requests\"",
    "\"storage_resource\"",
    "\"channels\"",
    "\"api\"",
    "\"cli\"",
    "\"web_interface\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"bandwidth\"",
    "\"latency\"",
    "\"speed\"",
    "\"memory\"",
    "\"cache\"",
    "\"capacity\"",
    "\"firstname\"",
    "\"surname\"",
    "\"username\"",
    "\"password\"",
    "\"acronym\"",
    "\"command\"",
    "\"digest\"",
    "\"url\"",
    "\"programming_language\"",
    "\"information_returned\"",
    "\"application_code\"",
    "\"size\"",
    "\"file_name\"",
    "\"category\"",
    "\"component\"",
    "\"description\"",
    "\"birthday\"",
    "\"email\"",
    "\"version\"",
    "\"license\"",
    "<LICENSE_TYPE>",
    "\"cores\"",
    "\"architecture\"",
    "\"operation\"",
    "<ARCHITECTURE_VALUE>",
    "<FLOATING_POINT>",
    "<NATURAL_NUMBER>",
    "<DATE_US>",
    "<STRING>",
  };

}
